version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: tg-server-manager
    restart: unless-stopped
    network_mode: "host"
    env_file:
      - .env
    environment:
      - RUST_LOG=debug
      - BOT_TOKEN
      - ALLOWED_USERS
      - SERVER_MAC
      - ROUTER_SSH_PORT
      - ROUTER_SSH_USER
      - SERVER_SSH_PORT
      - SERVER_SSH_USER